Repository BOM-A-3/blog-news-feed, pull requests merged in 2023-11, with the labels that each got.

#1 프로젝트 디렉토리 구조 설정
  .gitignore
  src/main/java/com/bom/newsfeed/domain/comment/entity/Comment.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
  src/main/java/com/bom/newsfeed/domain/post/entity/Post.java
  src/main/java/com/bom/newsfeed/global/common/entity/BaseEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/applicatoin-local.yaml
Labels: enhancement

#4 회원 도메인 설계 및 구현
  src/main/java/com/bom/newsfeed/domain/member/constant/MemberRole.java
  src/main/java/com/bom/newsfeed/domain/member/dto/MemberDto.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
Labels: enhancement

#5 공통 오류 응답 포맷 구현
  src/main/java/com/bom/newsfeed/global/advice/GlobalExceptionHandler.java
  src/main/java/com/bom/newsfeed/global/common/dto/ErrorResponse.java
  src/main/java/com/bom/newsfeed/global/exception/ApiException.java
  src/main/java/com/bom/newsfeed/global/exception/ErrorCode.java
Labels: enhancement

#9 회원 API - 회원가입 구현
  build.gradle
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/SignupRequest.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
  src/main/java/com/bom/newsfeed/domain/member/repository/MemberRepository.java
  src/main/java/com/bom/newsfeed/domain/member/service/MemberService.java
  src/main/java/com/bom/newsfeed/global/exception/AlreadyExistMemberException.java
  src/main/java/com/bom/newsfeed/global/exception/AlreadyExistNicknameException.java
  src/main/java/com/bom/newsfeed/global/exception/MemberNotFoundException.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: enhancement

#10 로그인 API 구현 및 Jwt 인증/인가 처리 구현
  src/main/java/com/bom/newsfeed/domain/member/dto/MemberDto.java
  src/main/java/com/bom/newsfeed/global/auth/TokenDto.java
  src/main/java/com/bom/newsfeed/global/auth/UserDetailsService.java
  src/main/java/com/bom/newsfeed/global/common/dto/LoginRequest.java
  src/main/java/com/bom/newsfeed/global/config/SecurityConfig.java
  src/main/java/com/bom/newsfeed/global/exception/AccessDeniedException.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/bom/newsfeed/global/security/AuthenticationEntryPointImpl.java
  src/main/java/com/bom/newsfeed/global/security/UserDetailsImpl.java
  src/main/java/com/bom/newsfeed/global/security/UserDetailsServiceImpl.java
  src/main/java/com/bom/newsfeed/global/util/JwtUtil.java
Labels: enhancement

#11 Jpa Auditing 설정 추가 - CreatedBy, ModifiedBy
  src/main/java/com/bom/newsfeed/global/config/AuditingConfig.java
Labels: enhancement

#12 SecurityConfig 에러 수정
  src/main/java/com/bom/newsfeed/global/config/SecurityConfig.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthorizationFilter.java
Labels: bug

#13 1차 main 병합
  build.gradle
  src/main/java/com/bom/newsfeed/domain/member/constant/MemberRole.java
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/member/dto/MemberDto.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/SignupRequest.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
  src/main/java/com/bom/newsfeed/domain/member/repository/MemberRepository.java
  src/main/java/com/bom/newsfeed/domain/member/service/MemberService.java
  src/main/java/com/bom/newsfeed/domain/post/controller/PostController.java
  src/main/java/com/bom/newsfeed/domain/post/dto/PostRequestDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/PostResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/entity/Post.java
  src/main/java/com/bom/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/com/bom/newsfeed/domain/post/service/PostService.java
  src/main/java/com/bom/newsfeed/global/advice/GlobalExceptionHandler.java
  src/main/java/com/bom/newsfeed/global/auth/TokenDto.java
  src/main/java/com/bom/newsfeed/global/auth/UserDetailsService.java
  src/main/java/com/bom/newsfeed/global/common/dto/ErrorResponse.java
  src/main/java/com/bom/newsfeed/global/common/dto/LoginRequest.java
  src/main/java/com/bom/newsfeed/global/common/entity/BaseEntity.java
  src/main/java/com/bom/newsfeed/global/config/AuditingConfig.java
  src/main/java/com/bom/newsfeed/global/config/SecurityConfig.java
  src/main/java/com/bom/newsfeed/global/exception/AccessDeniedException.java
  src/main/java/com/bom/newsfeed/global/exception/AlreadyExistMemberException.java
  src/main/java/com/bom/newsfeed/global/exception/AlreadyExistNicknameException.java
  src/main/java/com/bom/newsfeed/global/exception/ApiException.java
  src/main/java/com/bom/newsfeed/global/exception/ErrorCode.java
  src/main/java/com/bom/newsfeed/global/exception/MemberNotFoundException.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/bom/newsfeed/global/security/AuthenticationEntryPointImpl.java
  src/main/java/com/bom/newsfeed/global/security/UserDetailsImpl.java
  src/main/java/com/bom/newsfeed/global/security/UserDetailsServiceImpl.java
  src/main/java/com/bom/newsfeed/global/util/JwtUtil.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: enhancement

#15 Git ignore 파일 오타 수정
  .gitignore
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/bom/newsfeed/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bom/newsfeed/domain/comment/dto/CommentResponseDto.java
  src/main/java/com/bom/newsfeed/domain/comment/entity/Comment.java
  src/main/java/com/bom/newsfeed/domain/comment/repository/CommentRepository.java
  src/main/java/com/bom/newsfeed/domain/comment/service/CommentService.java
Labels: enhancement

#16 카테고리 도메인 구현
  src/main/java/com/bom/newsfeed/domain/category/constant/CategoryType.java
  src/main/java/com/bom/newsfeed/domain/category/entity/Category.java
Labels: enhancement

#17 회원 API 구현
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/ChangePasswordRequest.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/UpdateProfileRequest.java
  src/main/java/com/bom/newsfeed/domain/member/dto/response/UpdateProfileResponse.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
  src/main/java/com/bom/newsfeed/domain/member/service/MemberService.java
  src/main/java/com/bom/newsfeed/global/exception/ChangePasswordMissMatchException.java
  src/main/java/com/bom/newsfeed/global/exception/ErrorCode.java
Labels: enhancement

#18 회원 인증 정보 가져오는 커스텀 어노테이션 구현
  src/main/java/com/bom/newsfeed/global/annotation/CurrentMember.java
Labels: enhancement

#20 MemberDTo에서 Member 엔티티 변환 메소드 추가
  src/main/java/com/bom/newsfeed/domain/member/dto/MemberDto.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
Labels: enhancement

#22 Refresh Token 예외 추가
  src/main/java/com/bom/newsfeed/global/exception/InvalidRefreshTokenException.java
Labels: enhancement

#24 댓글 API 구현 완료
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/bom/newsfeed/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bom/newsfeed/domain/comment/repository/CommentRepository.java
  src/main/java/com/bom/newsfeed/domain/comment/service/CommentService.java
  src/main/java/com/bom/newsfeed/global/common/dto/DefaultRes.java
  src/main/java/com/bom/newsfeed/global/common/dto/ResponseMessage.java
  src/main/java/com/bom/newsfeed/global/common/dto/StatusCode.java
Labels: enhancement

#26 팔로우 API 구현
  src/main/java/com/bom/newsfeed/domain/follow/controller/FollowController.java
  src/main/java/com/bom/newsfeed/domain/follow/entity/Follow.java
  src/main/java/com/bom/newsfeed/domain/follow/entity/FollowPk.java
  src/main/java/com/bom/newsfeed/domain/follow/repository/FollowRepository.java
  src/main/java/com/bom/newsfeed/domain/follow/service/FollowService.java
  src/main/java/com/bom/newsfeed/global/exception/AlreadyExistFollowingException.java
  src/main/java/com/bom/newsfeed/global/exception/ErrorCode.java
  src/main/java/com/bom/newsfeed/global/exception/FollowingNotFoundException.java
Labels: enhancement

#29 2차 메인 병합
  src/main/java/com/bom/newsfeed/domain/auth/controller/AuthController.java
  src/main/java/com/bom/newsfeed/domain/auth/service/AuthService.java
  src/main/java/com/bom/newsfeed/domain/category/constant/CategoryType.java
  src/main/java/com/bom/newsfeed/domain/category/entity/Category.java
  src/main/java/com/bom/newsfeed/domain/category/repository/CategoryRepository.java
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/bom/newsfeed/domain/comment/dto/CommentRequestDto.java
  src/main/java/com/bom/newsfeed/domain/comment/repository/CommentRepository.java
  src/main/java/com/bom/newsfeed/domain/comment/service/CommentService.java
  src/main/java/com/bom/newsfeed/domain/follow/controller/FollowController.java
  src/main/java/com/bom/newsfeed/domain/follow/entity/Follow.java
  src/main/java/com/bom/newsfeed/domain/follow/entity/FollowPk.java
  src/main/java/com/bom/newsfeed/domain/follow/repository/FollowRepository.java
  src/main/java/com/bom/newsfeed/domain/follow/service/FollowService.java
  src/main/java/com/bom/newsfeed/domain/like/controller/LikeController.java
  src/main/java/com/bom/newsfeed/domain/like/dto/LikeResponseDto.java
  src/main/java/com/bom/newsfeed/domain/like/entity/Like.java
  src/main/java/com/bom/newsfeed/domain/like/repository/LikeRepository.java
  src/main/java/com/bom/newsfeed/domain/like/service/LikeService.java
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/member/dto/MemberDto.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/ChangePasswordRequest.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/UpdateProfileRequest.java
  src/main/java/com/bom/newsfeed/domain/member/dto/response/UpdateProfileResponse.java
  src/main/java/com/bom/newsfeed/domain/member/entity/Member.java
  src/main/java/com/bom/newsfeed/domain/member/service/MemberService.java
  src/main/java/com/bom/newsfeed/domain/post/controller/PostController.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetCommentResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetLikeResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetPostAllResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetPostFIleResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/PostRequestDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/PostResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/SelectPostResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/entity/Post.java
  src/main/java/com/bom/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/com/bom/newsfeed/domain/post/service/PostService.java
  src/main/java/com/bom/newsfeed/domain/postfile/dto/PostFileRequestDto.java
  src/main/java/com/bom/newsfeed/domain/postfile/entity/FileType.java
  src/main/java/com/bom/newsfeed/domain/postfile/entity/PostFile.java
  src/main/java/com/bom/newsfeed/domain/postfile/repository/PostFileRepository.java
  src/main/java/com/bom/newsfeed/domain/postfile/service/PostFileService.java
  src/main/java/com/bom/newsfeed/global/annotation/CurrentMember.java
  src/main/java/com/bom/newsfeed/global/common/dto/DefaultRes.java
  src/main/java/com/bom/newsfeed/global/common/dto/ResponseMessage.java
  src/main/java/com/bom/newsfeed/global/common/dto/StatusCode.java
  src/main/java/com/bom/newsfeed/global/config/RedisConfig.java
  src/main/java/com/bom/newsfeed/global/config/SecurityConfig.java
  src/main/java/com/bom/newsfeed/global/exception/AlreadyExistFollowingException.java
  src/main/java/com/bom/newsfeed/global/exception/ChangePasswordMissMatchException.java
  src/main/java/com/bom/newsfeed/global/exception/ErrorCode.java
  src/main/java/com/bom/newsfeed/global/exception/FollowingNotFoundException.java
  src/main/java/com/bom/newsfeed/global/exception/InvalidRefreshTokenException.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthenticationFilter.java
  src/main/java/com/bom/newsfeed/global/filter/JwtAuthorizationFilter.java
  src/main/java/com/bom/newsfeed/global/util/MemberUtil.java
  src/main/java/com/bom/newsfeed/global/util/RedisUtil.java
  src/main/resources/application-local.yaml
  src/main/resources/application.yaml
Labels: enhancement

#34 Comment API 수정
  .github/workflows/cicd.yml
  appspec.yml
  build.gradle
  deploy.sh
  src/main/java/com/bom/newsfeed/BlogNewsFeedApplication.java
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/bom/newsfeed/domain/comment/service/CommentService.java
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/global/common/constant/ErrorCode.java
  src/main/java/com/bom/newsfeed/global/config/S3Config.java
  src/main/java/com/bom/newsfeed/global/exception/CommentAccessDeniedException.java
  src/main/java/com/bom/newsfeed/global/exception/CommentNotFoundException.java
  src/main/java/com/bom/newsfeed/global/exception/PostNotFoundException.java
  src/main/java/com/bom/newsfeed/global/util/S3Uploader.java
  src/main/resources/application.yaml
Labels: enhancement

#37 피드 API 구현
  build.gradle
  src/main/java/com/bom/newsfeed/domain/category/constant/CategoryType.java
  src/main/java/com/bom/newsfeed/domain/follow/entity/Follow.java
  src/main/java/com/bom/newsfeed/domain/follow/repository/FollowRepository.java
  src/main/java/com/bom/newsfeed/domain/post/controller/FeedController.java
  src/main/java/com/bom/newsfeed/domain/post/dto/FeedResponse.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetPostAllResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetPostFIleResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/dto/SearchFeedCondition.java
  src/main/java/com/bom/newsfeed/domain/post/repository/FeedRepository.java
  src/main/java/com/bom/newsfeed/domain/post/repository/FeedRepositoryCustom.java
  src/main/java/com/bom/newsfeed/domain/post/repository/FeedRepositoryCustomImpl.java
  src/main/java/com/bom/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/com/bom/newsfeed/domain/post/service/FeedService.java
  src/main/java/com/bom/newsfeed/global/common/constant/ResponseCode.java
  src/main/java/com/bom/newsfeed/global/config/QueryDslConfig.java
Labels: enhancement

#41 회원가입 API 버그수정
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/SignupRequest.java
Labels: bug

#42 피드 API Swagger 추가
  src/main/java/com/bom/newsfeed/domain/post/controller/FeedController.java
Labels: enhancement

#44 CommentController modify and LikeController modify and ResponseCode modify
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/bom/newsfeed/domain/like/controller/LikeController.java
  src/main/java/com/bom/newsfeed/domain/post/controller/PostController.java
  src/main/java/com/bom/newsfeed/domain/post/dto/PostRequestDto.java
  src/main/java/com/bom/newsfeed/global/common/constant/ResponseCode.java
  src/main/java/com/bom/newsfeed/global/config/S3Config.java
  src/main/java/com/bom/newsfeed/global/util/S3Uploader.java
Labels: enhancement

#49 comment delete 수정
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
  src/main/java/com/bom/newsfeed/domain/comment/service/CommentService.java
  src/main/java/com/bom/newsfeed/domain/post/service/PostService.java
  src/main/resources/application-local.yaml
  src/main/resources/application-prod.yaml
  src/main/resources/application.yaml
Labels: enhancement

#50 CommentController
  .gitignore
  gradlew
  src/main/java/com/bom/newsfeed/domain/comment/controller/CommentController.java
Labels: enhancement

#54 회원 API 수정
  src/main/java/com/bom/newsfeed/domain/member/dto/request/SignupRequest.java
Labels: enhancement

#55 main 병합
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/member/dto/request/SignupRequest.java
  src/main/java/com/bom/newsfeed/global/common/constant/ResponseCode.java
  src/main/java/com/bom/newsfeed/global/config/SecurityConfig.java
Labels: bug, enhancement

#57 버그 수정후 main 릴리즈
  src/main/java/com/bom/newsfeed/domain/category/constant/CategoryType.java
  src/main/java/com/bom/newsfeed/domain/follow/controller/FollowController.java
  src/main/java/com/bom/newsfeed/domain/member/controller/MemberController.java
  src/main/java/com/bom/newsfeed/domain/post/dto/GetAllPostResponseDto.java
  src/main/java/com/bom/newsfeed/domain/post/service/FeedService.java
  src/main/java/com/bom/newsfeed/global/common/constant/ResponseCode.java
Labels: bug, enhancement

#59 The "Last Dance"
  src/main/java/com/bom/newsfeed/domain/follow/controller/FollowController.java
  src/main/java/com/bom/newsfeed/domain/follow/repository/FollowRepository.java
  src/main/java/com/bom/newsfeed/domain/follow/service/FollowService.java
  src/main/java/com/bom/newsfeed/domain/post/controller/PostController.java
  src/main/java/com/bom/newsfeed/domain/post/dto/PostUpdateRequestDto.java
  src/main/java/com/bom/newsfeed/domain/post/repository/PostRepository.java
  src/main/java/com/bom/newsfeed/domain/post/service/FeedService.java
  src/main/java/com/bom/newsfeed/domain/postfile/service/PostFileService.java
  src/main/resources/application.yaml
Labels: enhancement
